<?php
/**
 * Created by PhpStorm.
 * User: liuwei
 * Date: 2018/9/1
 * Time: 上午11:25
 */

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Redis;
use Workerman\Worker;

class MessageServer extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'MessageServer {cmd=start} {mode=""}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'as a mail server';


    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $ws_worker = new Worker("websocket://0.0.0.0:2000");

        $ws_worker->count = 1;

        $ws_worker->onMessage = function($connection, $data)
        {
            echo $data."\n";
            Redis::set('worker' ,$data);

            $connection->send('hello ' . $data);
        };

        Worker::runAll();

    }

    public function option($key = null)
    {
        return parent::option($key); // TODO: Change the autogenerated stub
    }

    public function argument($key = null)
    {
        return parent::argument($key); // TODO: Change the autogenerated stub
    }

}